### PR TITLE
Updated MarkDown generator version

### PR DESCRIPTION
**Pull request by bwosborne2**
Old version is unavailable

Signed-off-by: Bruce Osborne <bwosborne@gmail.com>

### CODE REVIEW

**Comment by cdjackson** [comment]
@bwosborne2 we should try and keep separate PRs for different issues. Here you are mixing two things - the generator version, and you've also updated documentation. This means we can't merge anything until both are correct, and makes traceability a bit difficult since the PR doesn't mention docs.

I need to see if we can update to this version of the generator - it may not work. As I said elsewhere, we need to use a custom version of the generator to get some of the extra features included, and therefore I don't think that this will work fully with the latest public version.

Some of my changes were included into the master, but I think not all and I need to check if this is needed for the docs here.

**Comment by cdjackson** [comment]
I've checked and v2.3 includes my changes, so this should be fine to merge.

**Comment by cdjackson** [comment]
And thanks @bwosborne2

**Comment by bwosborne2** [comment]
Sorry for the mix. I am still learning & did not expect that to happen. I am still learning but at least I can do signed PRs using VSCode now.

**Comment by cdjackson** [comment]
No problem Bruce - thnaks.

**Pull request merged**
